export const userTypes = {
  USER_LOADING: 'USER_LOADING',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAILED: 'USER_AUTH_FAILED',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILED: 'GET_USER_FAILED',
  UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
  UPDATE_USER_DATA_FAILED: 'UPDATE_USER_DATA_FAILED',
  LOGOUT: 'LOGOUT',
};

export const uiTypes = {
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  LOADING_UI: 'LOADING_UI',
  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',
  LOADING_UI_FINISHED: 'LOADING_UI_FINISHED',
};

export const dataTypes = {
  SET_POSTS: 'SET_POSTS',
  SET_PROFILE_DATA: 'SET_PROFILE_DATA',
  LOADING_DATA: 'LOADING_DATA',
};
