export const postTypes = {
  FETCH_POSTS: 'FETCH_POSTS',
};

export const userTypes = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  RESET_AUTH_FORM_ERRORS: 'RESET_AUTH_FORM_ERRORS',
  LOGOUT: 'LOGOUT',
};
